In [3]:
import numpy as np
a = np.array([10,20,30,40])
b = np.arange(4) #b:[0 1 2 3]

print("a:",a,"b:",b)
print("a+b:",a+b)
print("a-b:",a-b)
print("a*b:",a*b) #a*b 逐位相乘 除号'/'同理
print("b**2",b**2) #[0 1 4 9]
print(np.sin(a),'\n',np.cos(a))
print(np.dot(a,b)) #点乘，10*0 + 20*1 + 30*2 + 40*3 = 0+20+60+120 = 200
print(a<24) #[ True  True False False]
print(a[a<24])
print("111111111111111111111111111111111111111111111111111")
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A@B)
print("22222222222222222222222222222222222")
a = np.random.random((2,4))
print("a:",a)
print("np.sum(a):",np.sum(a,axis=1))
print("np.min(a):",np.min(a))
print("np.max(a):",np.max(a))

a: [10 20 30 40] b: [0 1 2 3]
a+b: [10 21 32 43]
a-b: [10 19 28 37]
a*b: [  0  20  60 120]
b**2 [0 1 4 9]
[-0.54402111  0.91294525 -0.98803162  0.74511316] 
 [-0.83907153  0.40808206  0.15425145 -0.66693806]
200
[ True  True False False]
[10 20]
111111111111111111111111111111111111111111111111111
[[19 22]
 [43 50]]
22222222222222222222222222222222222


TypeError: random() got an unexpected keyword argument 'dtype'

###03 相关操作
- `+ - * /`均为逐位相乘
- `np.sin() np.cos()` 三角运算
- `np.array()` 矩阵运算
- `np.dot() A@B`均为数学里面的矩阵乘法 而 A*B为逐位相乘
- `np.sum np.min np.max` axis=1每一行 axis=0列