In [27]:
import numpy as np
A = np.arange(14,2,-1).reshape((3,4))
print("matrix A:\n", A)

print("np.argmin:", np.argmin(A)) #返回索引
print("np.argmax:", np.argmax(A))
print("np.mean:", np.average(A)) #等价于 A.mean()
print("np.cumsum :", np.cumsum(A))
print("累差np.diff:\n", np.diff(A))
print("np.nonzero:\n", np.nonzero(A)) 
print("###############################################")
print("np.sort:\n", np.sort(A))
#print("A:\n",A,"A^T:\n",A.T) #or u can also use np.transpose(A)
print("np.clip(A,n,m):\n", np.clip(A,7.5,9))
print("A:",A,"\nA.mean(axis=0)",A.mean(axis=0),"\nA.mean(axis=1)",A.mean(axis=1))

matrix A:
 [[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
np.argmin: 11
np.argmax: 0
np.mean: 8.5
np.cumsum : [ 14  27  39  50  60  69  77  84  90  95  99 102]
累差np.diff:
 [[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]
np.nonzero:
 (array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))
###############################################
np.sort:
 [[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]
np.clip(A,n,m):
 [[9.  9.  9.  9. ]
 [9.  9.  8.  7.5]
 [7.5 7.5 7.5 7.5]]
A: [[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]] 
A.mean(axis=0) [10.  9.  8.  7.] 
A.mean(axis=1) [12.5  8.5  4.5]


###04 相关操作2
- `arg -> argument` 参数
- `np.argmin np.argmax` 分别返回矩阵的最小，最大值的索引
- `np.average(A) <-> A.mean()` 返回平均值
- `cumsum -> cumulate sum` 求和，索引[0~n-1],[i]对应第一个加到第i+1个
- `np.nonzero` 二维矩阵返回两个array,A[array1[i]][array2[i]]代表其为非零的
- `np.sort:` 逐行排序
- `np.transpose(A) <-> A.T` A的转置， 复习：np.dot(A,B)数学里面的矩阵相乘
- `np.clip(A,n,m)` A矩阵中，小于n的数都变为n,大于的都变为m. clip,专业术语裁剪
- `axis=0 对列，axis=1 对行`