In [20]:
import numpy as np
A = np.arange(3,15)
print(A)
print("A[2]:",A[2])
print("############################")
B = A.reshape((3,4))
print("B=A.reshape((3,4)):\n", B)
print("B[2]:",B[2])
print("B[2][1]:", B[2][1]) # and u can also B[2,1] <-> B[2][1]
print("22222222222222222222222222222222222")
print("B[1,:]:", B[1][:])
print("B[1][1:3]", B[1][1:3])
print("3333333333333333333333333333333333333")
for row in B:
    print(row)
for column in B.T:
    print(column)
print("attention: B = A.reshape((3,4))")
print(B)
print("make matrix B flat:", B.flatten())
for item in B.flat:
    print(item)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
A[2]: 5
############################
B=A.reshape((3,4)):
 [[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
B[2]: [11 12 13 14]
B[2][1]: 12
22222222222222222222222222222222222
B[1,:]: [ 7  8  9 10]
B[1][1:3] [8 9]
3333333333333333333333333333333333333
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
attention: B = A.reshape((3,4))
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
make matrix B flat: [ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


###05-Index Of Numpy
- `遍历行` for row in A: print(row)
- `遍历列` for column in A.T: print(column) # A.T <-> np.transpose(A)
- `索引跟编程语言差不多[0~n-1][0~n-1]`
- `A = arange(3,15).reshape((3,4))` 如果你想让他展平，你可以 A.flatten()