In [27]:
import numpy as np
A = np.array([1,1,1])
B = np.array([2,2,2])
AvB = np.vstack((A,B)) #vertical stack 垂直堆叠
print(A,A.shape,B,B.shape)
print(AvB,AvB.shape)
AhB = np.hstack((A,B)) #horizontal stack 水平堆叠
print(AhB,AhB.shape)
print("##############################################")
print(A,A.shape)
print(A[:,np.newaxis],A[:,np.newaxis].shape)
print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
print(A,B)
C0 = np.concatenate((A[:,np.newaxis],B[:,np.newaxis]),axis = 0); print(C0)
C1 = np.concatenate((A[:,np.newaxis],B[:,np.newaxis]),axis = 1); print(C1)

[1 1 1] (3,) [2 2 2] (3,)
[[1 1 1]
 [2 2 2]] (2, 3)
[1 1 1 2 2 2] (6,)
##############################################
[1 1 1] (3,)
[[1]
 [1]
 [1]] (3, 1)
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[1 1 1] [2 2 2]
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]]
[[1 2]
 [1 2]
 [1 2]]


###Mergence Of Array
- `np.vstack(A,B)` 把矩阵A和B垂直堆叠
- `np.hstack(A,B)` 把矩阵A和B水平堆叠
- `A = np.array([1,1,1]), A[:, newaxis] -> [[1],[1],[1]]`加了一个维度
- `np.concatenate((),axis = 0/1)`多个数组合并，concatenate 把...联系起来
- `np.vstack和np.hstack都可以实现多个数组的合并`
###关键总结
- `A = np.array([1,1,1])` 这个是一维的, and it's shape is (3,)
- `B = A[newaxis,:]` 转为二维的，shape is (1,3)
- `C = A[:,newaxis]` shape is (3,1)