In [23]:
import numpy as np

array = np.array([[1,2,3],[2,3,4],[3,3,3]])
print(array)
print(array.ndim)
print(array.shape)
print(array.size)
print("########################################1")
array02 = np.array([2,23,4],dtype = np.float32)
print(array02.dtype)
print(np.zeros((3,4), dtype=np.int16))
print(np.ones((4,3)))
print("###################2")
print(np.empty((3,4)))
print("##################################3")
print(np.arange(10,20,2)) #[10 12 14 16 18]
print(np.arange(12).reshape((3,4)))
print(np.linspace(1,10,5))

[[1 2 3]
 [2 3 4]
 [3 3 3]]
2
(3, 3)
9
########################################1
float32
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
###################2
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
##################################3
[10 12 14 16 18]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 1.    3.25  5.5   7.75 10.  ]


###01-Creation
- `array.ndim` 几维
- `array.shape` n*m
- `array.size` 元素个数
###02-Associative_Operation
- `np.array(  , dtype)` 元素类型
- `np.zeros((n,m))` n*m的全零矩阵
- `np.ones((n,m))` n*m的全1矩阵
- `np.empty((n,m))` n*m的空矩阵
- `np.arange(默认0,终止位,步长)`
- `np.arange(12).reshape((3,4))` 3*4大小的从0-11，即[0,12)
- `np.linspace(n,m,z)` 从n到m平均分为z个点
###总结
- `np.arange()是步长，np.linspace()是分段` 这两个also can .reshape