In [28]:
import numpy as np
a1 = np.array([2,23,4], dtype = np.int64)
a2 = np.array([2,23,4], dtype = np.int32)
print(a1.dtype,a2.dtype)
a3 = np.array([[2,23,4],[23,123,444]], dtype = np.int64); print(a3)
a4 = np.zeros((3,4)); print(a4, a4.ndim)
a5 = np.ones((3,4)); print(a5)
a6 = np.empty((3,4)); print(a6)
print('#########################################')
b1 = np.arange(12).reshape((3,4)); print(b)
b2 = np.linspace(1,10,8).reshape((2,4)); print(b2)

int64 int32
[[  2  23   4]
 [ 23 123 444]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 2
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
#########################################
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1.          2.28571429  3.57142857  4.85714286]
 [ 6.14285714  7.42857143  8.71428571 10.        ]]


### numpy about creation
- `np.array` 创建数组
- `dtype` 矩阵数据类型
- `[[],[]]` 2维
- `np.zeros((n,m))` n*m的全零矩阵
- `np.ones((n,m))` n*m的全1矩阵
- `np.empty((n,m))` n*m的空矩阵，速度最快
- `np.arange(sum).reshape((n,m))` 从0-sum的n*m矩阵
- `np.linspace(n,m,s)` 从n到m一共s段的数组，reshape后也可使其分段