In [1]:
import numpy as np

# 创建一个一维数组
arr1 = np.array([1, 2, 3, 4, 5])
print("一维数组:", arr1)

# 创建一个全零数组
zeros = np.zeros((3, 3))
print("\n全零数组:\n", zeros)

# 创建一个随机数组
random_arr = np.random.randn(2, 3)
print("\n随机数组:\n", random_arr)

一维数组: [1 2 3 4 5]

全零数组:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

随机数组:
 [[ 1.19329892 -0.22816994 -0.71473169]
 [ 0.39110017  0.34944707  0.78053737]]
